name: Master
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Install Node
        run: npm install node@16.13.1
      - name: Rebuild the dist/ directory
        run: npm run build
      - name: Google App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: mophead-app
          version: master
          credentials: ${{ secrets.GOOGLE_APP_ENGINE_CREDENTIALS}}
          flags: --no-cache
          deliverables: app.yaml
